/********************************************************************
* BetaDecayDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BetaDecayDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBetaDecayDict();
extern void G__cpp_setup_inheritanceBetaDecayDict();
extern void G__cpp_setup_typetableBetaDecayDict();
extern void G__cpp_setup_memvarBetaDecayDict();
extern void G__cpp_setup_globalBetaDecayDict();
extern void G__cpp_setup_memfuncBetaDecayDict();
extern void G__cpp_setup_funcBetaDecayDict();
extern void G__set_cpp_environmentBetaDecayDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BetaDecay.h"
#include "Correlator.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BetaDecayDictLN_TClass;
extern G__linked_taginfo G__BetaDecayDictLN_TBuffer;
extern G__linked_taginfo G__BetaDecayDictLN_TMemberInspector;
extern G__linked_taginfo G__BetaDecayDictLN_TObject;
extern G__linked_taginfo G__BetaDecayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BetaDecayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BetaDecayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BetaDecayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BetaDecayDictLN_Clock;
extern G__linked_taginfo G__BetaDecayDictLN_Tac;
extern G__linked_taginfo G__BetaDecayDictLN_GeDSSD;
extern G__linked_taginfo G__BetaDecayDictLN_Sega;
extern G__linked_taginfo G__BetaDecayDictLN_Pin;
extern G__linked_taginfo G__BetaDecayDictLN_Scint;
extern G__linked_taginfo G__BetaDecayDictLN_PID;
extern G__linked_taginfo G__BetaDecayDictLN_BetaDecayCorrelator;
extern G__linked_taginfo G__BetaDecayDictLN_BetaDecay;
extern G__linked_taginfo G__BetaDecayDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BetaDecayDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BetaDecayDictLN_TCutG;
extern G__linked_taginfo G__BetaDecayDictLN_Implant;
extern G__linked_taginfo G__BetaDecayDictLN_Decay;
extern G__linked_taginfo G__BetaDecayDictLN_Correlator;

/* STUB derived class for protected member access */
